#!/usr/bin/env python3
"""Build Resources/mozc-dict.txt from the Mozc open-source dictionary (ADR-034).

Mozc rows are `reading<TAB>lid<TAB>rid<TAB>cost<TAB>surface`; `id.def` names
the part of speech of each id. The right id (how an entry connects to what
follows) chooses the Gictionary connection classes:

    名詞,サ変接続        -> 3 4  and 50 51   (再起動 / 実装 take する forms)
    名詞,形容動詞語幹    -> 3 4  and 18 19   (簡単 takes な / に)
    名詞,*               -> 3 4
    副詞                 -> 24 0
    感動詞               -> 3 4

Only noun-like left ids are kept (名詞 / 接頭詞 compounds / 副詞 / 感動詞);
verbs and adjectives keep Gictionary's own conjugation rows. Entries above
the cost thresholds (Mozc cost = scaled -log probability, lower = common) are
dropped: common nouns at --max-cost, place and person names at
--max-proper-cost. Readings are hiragana, so the connection dictionary indexes
them without romaji conversion (ADR-033). Rows are ordered by cost so common
words come first in dictionary order.

    curl -sL -o /tmp/mozc/id.def https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/id.def
    for i in 0 1 2 3 4 5 6 7 8 9; do curl -sL -o /tmp/mozc/dictionary0$i.txt \\
        https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/dictionary0$i.txt; done
    python3 Tools/dict/build-mozc-connection-dict.py --mozc-dir /tmp/mozc --commit <sha> --output Resources/mozc-dict.txt

Mozc's dictionary is BSD-3-Clause (Google) with IPAdic-derived entries; see
Resources/DICTIONARY_THIRD_PARTY_NOTICES.txt.
"""

from __future__ import annotations

import argparse
import collections
import glob
import re
from pathlib import Path

HIRAGANA_READING = re.compile(r"^[ぁ-ゖー・]+$")
PROPER_CATEGORIES = {"名詞,固有名詞,地域", "名詞,固有名詞,人名"}
LEFT_KEEP = {"名詞", "接頭詞", "副詞", "感動詞"}
COMMON_CATEGORIES = {
    "名詞,一般", "名詞,サ変接続", "名詞,形容動詞語幹", "名詞,副詞可能", "名詞,数", "名詞,接尾", "名詞,代名詞",
    "名詞,固有名詞,一般", "名詞,固有名詞,組織", "副詞", "感動詞",
} | PROPER_CATEGORIES


def category(pos: list[str]) -> str:
    if pos[0] == "名詞":
        return "名詞,固有名詞," + pos[2] if pos[1] == "固有名詞" else "名詞," + pos[1]
    return pos[0]


def classes(categories: set[str]) -> list[tuple[str, str]]:
    rows = [("3", "4")]
    if "名詞,サ変接続" in categories:
        rows.append(("50", "51"))
    if "名詞,形容動詞語幹" in categories:
        rows.append(("18", "19"))
    if categories == {"副詞"}:
        rows = [("24", "")]
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--mozc-dir", type=Path, required=True, help="directory with id.def and dictionary0*.txt")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--commit", default="unknown", help="Mozc commit the source files were taken from")
    parser.add_argument("--max-cost", type=int, default=7500)
    parser.add_argument("--max-proper-cost", type=int, default=6000, help="for place and person names")
    args = parser.parse_args()

    ids: dict[int, list[str]] = {}
    for line in (args.mozc_dir / "id.def").read_text(encoding="utf-8").splitlines():
        number, pos = line.split(" ", 1)
        ids[int(number)] = pos.split(",")

    # (reading, surface) -> [min cost, right categories]
    entries: dict[tuple[str, str], list] = {}
    skipped = collections.Counter()
    for path in sorted(glob.glob(str(args.mozc_dir / "dictionary0*.txt"))):
        with open(path, encoding="utf-8") as f:
            for line in f:
                row = line.rstrip("\n").split("\t")
                if len(row) < 5:
                    continue
                reading, left, right, cost, surface = row[0], ids[int(row[1])], ids[int(row[2])], int(row[3]), row[4]
                if left[0] not in LEFT_KEEP:
                    skipped["left:" + left[0]] += 1
                    continue
                right_category = category(right)
                if right_category not in COMMON_CATEGORIES:
                    skipped["right:" + right_category] += 1
                    continue
                if cost > (args.max_proper_cost if right_category in PROPER_CATEGORIES else args.max_cost):
                    skipped["cost"] += 1
                    continue
                if not HIRAGANA_READING.match(reading):
                    skipped["reading"] += 1
                    continue
                if surface == reading:
                    skipped["surface == reading"] += 1  # the kana key itself; kana confirm covers it
                    continue
                entry = entries.setdefault((reading, surface), [cost, set()])
                entry[0] = min(entry[0], cost)
                entry[1].add(right_category)

    ordered = sorted(entries.items(), key=lambda item: (item[1][0], item[0]))
    lines = [
        "# Generated by Tools/dict/build-mozc-connection-dict.py from the Mozc open-source dictionary",
        f"# (google/mozc {args.commit}, src/data/dictionary_oss). Do not edit by hand.",
        f"# max-cost={args.max_cost} max-proper-cost={args.max_proper_cost} entries={len(ordered)}",
        "# License: see DICTIONARY_THIRD_PARTY_NOTICES.txt (Mozc BSD-3-Clause, IPAdic).",
    ]
    rows = 0
    for (reading, surface), (_, categories) in ordered:
        for in_class, out_class in classes(categories):
            lines.append(f"{reading}\t{surface}\t{in_class}\t{out_class}")
            rows += 1
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    by_category = collections.Counter(c for _, (_, cats) in ordered for c in cats)
    print(f"wrote {rows} rows for {len(ordered)} entries to {args.output}")
    print("by right category:", dict(by_category.most_common()))
    print("skipped:", dict(skipped.most_common(12)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
